spring.application.name=06-sb-manytomany-unidirectional-mapping

spring.datasource.url= jdbc:mysql://localhost:3306/sb_jpa
spring.datasource.username= root
spring.datasource.password= Singh@11
spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql= true


